title: Tensor Field
email: woof@heisen.me
description: Skoltech project
baseurl: "/TensorField" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ivan-kuzmin
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
